package net.jtk.darkroleplay.main;

import net.jtk.darkroleplay.blocks.blockPlaceholder;
import net.jtk.darkroleplay.blocks.Anvil.Anvil;
import net.jtk.darkroleplay.blocks.Anvil.TileEntityCustomAnvil;
import net.jtk.darkroleplay.blocks.Anvil.customRendererAnvil;
import net.jtk.darkroleplay.blocks.AppleGreen.AppleHangingGreen;
import net.jtk.darkroleplay.blocks.AppleGreen.AppleStandingGreen;
import net.jtk.darkroleplay.blocks.AppleGreen.TileEntityCustomAppleHangingGreen;
import net.jtk.darkroleplay.blocks.AppleGreen.TileEntityCustomAppleStandingGreen;
import net.jtk.darkroleplay.blocks.AppleGreen.customRendererAppleHangingGreen;
import net.jtk.darkroleplay.blocks.AppleGreen.customRendererAppleStandingGreen;
import net.jtk.darkroleplay.blocks.AppleRed.AppleHangingRed;
import net.jtk.darkroleplay.blocks.AppleRed.AppleStandingRed;
import net.jtk.darkroleplay.blocks.AppleRed.TileEntityCustomAppleHangingRed;
import net.jtk.darkroleplay.blocks.AppleRed.TileEntityCustomAppleStandingRed;
import net.jtk.darkroleplay.blocks.AppleRed.customRendererAppleHangingRed;
import net.jtk.darkroleplay.blocks.AppleRed.customRendererAppleStandingRed;
import net.jtk.darkroleplay.blocks.AppleYellow.AppleHangingYellow;
import net.jtk.darkroleplay.blocks.AppleYellow.AppleStandingYellow;
import net.jtk.darkroleplay.blocks.AppleYellow.TileEntityCustomAppleHangingYellow;
import net.jtk.darkroleplay.blocks.AppleYellow.TileEntityCustomAppleStandingYellow;
import net.jtk.darkroleplay.blocks.AppleYellow.customRendererAppleHangingYellow;
import net.jtk.darkroleplay.blocks.AppleYellow.customRendererAppleStandingYellow;
import net.jtk.darkroleplay.blocks.Barrels.BarrelGunPowder;
import net.jtk.darkroleplay.blocks.Barrels.BarrelClosed;
import net.jtk.darkroleplay.blocks.Barrels.BarrelEmpty;
import net.jtk.darkroleplay.blocks.Barrels.TileEntityCustomBarrelClosed;
import net.jtk.darkroleplay.blocks.Barrels.TileEntityCustomBarrelEmpty;
import net.jtk.darkroleplay.blocks.Barrels.TileEntityCustomBarrelGunPowder;
import net.jtk.darkroleplay.blocks.Barrels.customRendererBarrelClosed;
import net.jtk.darkroleplay.blocks.Barrels.customRendererBarrelEmpty;
import net.jtk.darkroleplay.blocks.Barrels.customRendererBarrelGunPowder;
import net.jtk.darkroleplay.blocks.Books.BookOne;
import net.jtk.darkroleplay.blocks.Books.TileEntityCustomBookOne;
import net.jtk.darkroleplay.blocks.Books.customRendererBookOne;
import net.jtk.darkroleplay.blocks.Buckets.BucketWater;
import net.jtk.darkroleplay.blocks.Buckets.BucketDirt;
import net.jtk.darkroleplay.blocks.Buckets.BucketEmpty;
import net.jtk.darkroleplay.blocks.Buckets.BucketFlowerOne;
import net.jtk.darkroleplay.blocks.Buckets.TileEntityCustomBucketDirt;
import net.jtk.darkroleplay.blocks.Buckets.TileEntityCustomBucketEmpty;
import net.jtk.darkroleplay.blocks.Buckets.TileEntityCustomBucketFlowerOne;
import net.jtk.darkroleplay.blocks.Buckets.TileEntityCustomBucketWater;
import net.jtk.darkroleplay.blocks.Buckets.customRendererBucketDirt;
import net.jtk.darkroleplay.blocks.Buckets.customRendererBucketEmpty;
import net.jtk.darkroleplay.blocks.Buckets.customRendererBucketFlowerOne;
import net.jtk.darkroleplay.blocks.Buckets.customRendererBucketWater;
import net.jtk.darkroleplay.blocks.Cauldrons.Cauldron;
import net.jtk.darkroleplay.blocks.Cauldrons.CauldronCookingOne;
import net.jtk.darkroleplay.blocks.Cauldrons.CauldronCookingTwo;
import net.jtk.darkroleplay.blocks.Cauldrons.TileEntityCustomCauldron;
import net.jtk.darkroleplay.blocks.Cauldrons.TileEntityCustomCauldronCookingOne;
import net.jtk.darkroleplay.blocks.Cauldrons.TileEntityCustomCauldronCookingTwo;
import net.jtk.darkroleplay.blocks.Cauldrons.customRendererCauldron;
import net.jtk.darkroleplay.blocks.Cauldrons.customRendererCauldronCookingOne;
import net.jtk.darkroleplay.blocks.Cauldrons.customRendererCauldronCookingTwo;
import net.jtk.darkroleplay.blocks.Chain.Chain;
import net.jtk.darkroleplay.blocks.Chain.TileEntityCustomChain;
import net.jtk.darkroleplay.blocks.Chain.customRendererChain;
import net.jtk.darkroleplay.blocks.ChoppingBlock.ChoppingBlock;
import net.jtk.darkroleplay.blocks.ChoppingBlock.TileEntityCustomChoppingBlock;
import net.jtk.darkroleplay.blocks.ChoppingBlock.customRendererChoppingBlock;
import net.jtk.darkroleplay.blocks.Crate.Crate;
import net.jtk.darkroleplay.blocks.Crate.TileEntityCustomCrate;
import net.jtk.darkroleplay.blocks.Crate.customRendererCrate;
import net.jtk.darkroleplay.blocks.DungeonChest.DungeonChest;
import net.jtk.darkroleplay.blocks.DungeonChest.TileEntityCustomDungeonChest;
import net.jtk.darkroleplay.blocks.DungeonChest.customRendererDungeonChest;
import net.jtk.darkroleplay.blocks.Firepits.LargeFirepit;
import net.jtk.darkroleplay.blocks.Firepits.SmallFirepit;
import net.jtk.darkroleplay.blocks.Firepits.TileEntityCustomLargeFirepit;
import net.jtk.darkroleplay.blocks.Firepits.TileEntityCustomSmallFirepit;
import net.jtk.darkroleplay.blocks.Firepits.customRendererLargeFirepit;
import net.jtk.darkroleplay.blocks.Firepits.customRendererSmallFirepit;
import net.jtk.darkroleplay.blocks.Grindstone.Grindstone;
import net.jtk.darkroleplay.blocks.Grindstone.TileEntityCustomGrindstone;
import net.jtk.darkroleplay.blocks.Grindstone.customRendererGrindstone;
import net.jtk.darkroleplay.blocks.HangingBridge.HangingBridgeOne;
import net.jtk.darkroleplay.blocks.HangingBridge.HangingBridgeTwo;
import net.jtk.darkroleplay.blocks.HangingBridge.TileEntityCustomHangingBridgeOne;
import net.jtk.darkroleplay.blocks.HangingBridge.TileEntityCustomHangingBridgeTwo;
import net.jtk.darkroleplay.blocks.HangingBridge.customRendererHangingBridgeOne;
import net.jtk.darkroleplay.blocks.HangingBridge.customRendererHangingBridgeTwo;
import net.jtk.darkroleplay.blocks.Hook.Hook;
import net.jtk.darkroleplay.blocks.Hook.TileEntityCustomHook;
import net.jtk.darkroleplay.blocks.Hook.customRendererHook;
import net.jtk.darkroleplay.blocks.KeyHanging.KeyHanging;
import net.jtk.darkroleplay.blocks.KeyHanging.TileEntityCustomKeyHanging;
import net.jtk.darkroleplay.blocks.KeyHanging.customRendererKeyHanging;
import net.jtk.darkroleplay.blocks.Mugs.MugBeer;
import net.jtk.darkroleplay.blocks.Mugs.MugEmpty;
import net.jtk.darkroleplay.blocks.Mugs.TileEntityCustomMugBeer;
import net.jtk.darkroleplay.blocks.Mugs.TileEntityCustomMugEmpty;
import net.jtk.darkroleplay.blocks.Mugs.customRendererMugBeer;
import net.jtk.darkroleplay.blocks.Mugs.customRendererMugEmpty;
import net.jtk.darkroleplay.blocks.Mushrooms.MushroomBrown;
import net.jtk.darkroleplay.blocks.Mushrooms.MushroomRed;
import net.jtk.darkroleplay.blocks.Mushrooms.TileEntityCustomMushroomBrown;
import net.jtk.darkroleplay.blocks.Mushrooms.TileEntityCustomMushroomRed;
import net.jtk.darkroleplay.blocks.Mushrooms.customRendererMushroomBrown;
import net.jtk.darkroleplay.blocks.Mushrooms.customRendererMushroomRed;
import net.jtk.darkroleplay.blocks.PearYellow.PearHangingYellow;
import net.jtk.darkroleplay.blocks.PearYellow.PearStandingYellow;
import net.jtk.darkroleplay.blocks.PearYellow.TileEntityCustomPearHangingYellow;
import net.jtk.darkroleplay.blocks.PearYellow.TileEntityCustomPearStandingYellow;
import net.jtk.darkroleplay.blocks.PearYellow.customRendererPearHangingYellow;
import net.jtk.darkroleplay.blocks.PearYellow.customRendererPearStandingYellow;
import net.jtk.darkroleplay.blocks.Potions.PotionEmpty;
import net.jtk.darkroleplay.blocks.Potions.PotionRegenerationOne;
import net.jtk.darkroleplay.blocks.Potions.TileEntityCustomPotionEmpty;
import net.jtk.darkroleplay.blocks.Potions.TileEntityCustomPotionRegenerationOne;
import net.jtk.darkroleplay.blocks.Potions.customRendererPotionEmpty;
import net.jtk.darkroleplay.blocks.Potions.customRendererPotionRegenerationOne;
import net.jtk.darkroleplay.blocks.Rope.Rope;
import net.jtk.darkroleplay.blocks.Rope.TileEntityCustomRope;
import net.jtk.darkroleplay.blocks.Rope.customRendererRope;
import net.jtk.darkroleplay.blocks.ShipSteeringWheel.ShipSteeringWheel;
import net.jtk.darkroleplay.blocks.ShipSteeringWheel.TileEntityCustomShipSteeringWheel;
import net.jtk.darkroleplay.blocks.ShipSteeringWheel.customRendererShipSteeringWheel;
import net.jtk.darkroleplay.blocks.Target.Target;
import net.jtk.darkroleplay.blocks.Target.TileEntityCustomTarget;
import net.jtk.darkroleplay.blocks.Target.customRendererTarget;
import net.jtk.darkroleplay.blocks.Tombstones.TileEntityCustomTombstoneOne;
import net.jtk.darkroleplay.blocks.Tombstones.TombstoneOne;
import net.jtk.darkroleplay.blocks.Tombstones.customRendererTombstoneOne;
import net.jtk.darkroleplay.blocks.TrainingsDummy.TileEntityCustomTrainingsDummy;
import net.jtk.darkroleplay.blocks.TrainingsDummy.TrainingsDummy;
import net.jtk.darkroleplay.blocks.TrainingsDummy.customRendererTrainingsDummy;
import net.jtk.darkroleplay.blocks.WallTorch.TileEntityCustomWallTorchEmpty;
import net.jtk.darkroleplay.blocks.WallTorch.TileEntityCustomWallTorchLit;
import net.jtk.darkroleplay.blocks.WallTorch.TileEntityCustomWallTorchUnlit;
import net.jtk.darkroleplay.blocks.WallTorch.WallTorchEmpty;
import net.jtk.darkroleplay.blocks.WallTorch.WallTorchLit;
import net.jtk.darkroleplay.blocks.WallTorch.WallTorchUnlit;
import net.jtk.darkroleplay.blocks.WallTorch.customRendererWallTorchEmpty;
import net.jtk.darkroleplay.blocks.WallTorch.customRendererWallTorchLit;
import net.jtk.darkroleplay.blocks.WallTorch.customRendererWallTorchUnlit;
import net.jtk.darkroleplay.guis.hud.DRPGuiFood;
import net.jtk.darkroleplay.guis.hud.DRPGuiHealth;
import net.jtk.darkroleplay.guis.hud.DRPGuiTypeOne;
import net.jtk.darkroleplay.handler.KeyBindingManager;
import net.jtk.darkroleplay.items.itemAppleGreen;
import net.jtk.darkroleplay.items.itemAppleYellow;
import net.jtk.darkroleplay.items.itemBatEar;
import net.jtk.darkroleplay.items.itemCoinBronze;
import net.jtk.darkroleplay.items.itemCoinGold;
import net.jtk.darkroleplay.items.itemCoinSilver;
import net.jtk.darkroleplay.items.itemDough;
import net.jtk.darkroleplay.items.itemFirewood;
import net.jtk.darkroleplay.items.itemFlour;
import net.jtk.darkroleplay.items.itemFurWolf;
import net.jtk.darkroleplay.items.itemPear;
import net.jtk.darkroleplay.items.itemPumpkinStew;
import net.jtk.darkroleplay.items.itemPurse;
import net.jtk.darkroleplay.items.itemVegieStew;
import net.jtk.darkroleplay.items.potionMana1;
import net.jtk.darkroleplay.items.Magic.itemScrollTeleport;
import net.jtk.darkroleplay.items.Rings.RingIron;
import net.minecraft.client.Minecraft;
import net.minecraft.client.resources.model.ModelResourceLocation;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraft.world.World;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.fml.client.FMLClientHandler;
import net.minecraftforge.fml.client.registry.ClientRegistry;
import net.minecraftforge.fml.common.FMLCommonHandler;
import net.minecraftforge.fml.common.registry.GameRegistry;


public class ClientProxy extends CommonProxy{
	
	public void registerCrafting(){
	}
	
	public void registerEvents(){
		MinecraftForge.EVENT_BUS.register(new DRPGuiTypeOne(Minecraft.getMinecraft()));
		MinecraftForge.EVENT_BUS.register(new DRPGuiFood(Minecraft.getMinecraft()));
		MinecraftForge.EVENT_BUS.register(new DRPGuiHealth(Minecraft.getMinecraft()));
		
		ClientRegistry.registerKeyBinding(KeyBindingManager.openCrafting);
		ClientRegistry.registerKeyBinding(KeyBindingManager.openInventory);
    	FMLCommonHandler.instance().bus().register(new KeyBindingManager());
	}
	
	public void registerTileEntity(){
		
	}
	
	public void bindTileEntity(){
		//TileEntitySpecialRenderer
		ClientRegistry.bindTileEntitySpecialRenderer(TileEntityCustomTarget.class, new customRendererTarget());
		ClientRegistry.bindTileEntitySpecialRenderer(TileEntityCustomDungeonChest.class,new customRendererDungeonChest());	
		ClientRegistry.bindTileEntitySpecialRenderer(TileEntityCustomCrate.class,new customRendererCrate());
		ClientRegistry.bindTileEntitySpecialRenderer(TileEntityCustomSmallFirepit.class, new customRendererSmallFirepit());
		ClientRegistry.bindTileEntitySpecialRenderer(TileEntityCustomLargeFirepit.class, new customRendererLargeFirepit());
		ClientRegistry.bindTileEntitySpecialRenderer(TileEntityCustomBucketEmpty.class, new customRendererBucketEmpty());
		ClientRegistry.bindTileEntitySpecialRenderer(TileEntityCustomBucketDirt.class, new customRendererBucketDirt());
		ClientRegistry.bindTileEntitySpecialRenderer(TileEntityCustomBucketFlowerOne.class, new customRendererBucketFlowerOne());
		ClientRegistry.bindTileEntitySpecialRenderer(TileEntityCustomBarrelEmpty.class, new customRendererBarrelEmpty());
		ClientRegistry.bindTileEntitySpecialRenderer(TileEntityCustomBarrelClosed.class, new customRendererBarrelClosed());
		ClientRegistry.bindTileEntitySpecialRenderer(TileEntityCustomChoppingBlock.class,new customRendererChoppingBlock());
		ClientRegistry.bindTileEntitySpecialRenderer(TileEntityCustomRope.class, new customRendererRope());
		ClientRegistry.bindTileEntitySpecialRenderer(TileEntityCustomCauldron.class, new customRendererCauldron());
		ClientRegistry.bindTileEntitySpecialRenderer(TileEntityCustomChain.class,new customRendererChain());
		ClientRegistry.bindTileEntitySpecialRenderer(TileEntityCustomGrindstone.class, new customRendererGrindstone());
		ClientRegistry.bindTileEntitySpecialRenderer(TileEntityCustomHangingBridgeOne.class, new customRendererHangingBridgeOne());
		ClientRegistry.bindTileEntitySpecialRenderer(TileEntityCustomHangingBridgeTwo.class, new customRendererHangingBridgeTwo());
		ClientRegistry.bindTileEntitySpecialRenderer(TileEntityCustomTombstoneOne.class, new customRendererTombstoneOne());
		ClientRegistry.bindTileEntitySpecialRenderer(TileEntityCustomBookOne.class, new customRendererBookOne());
		ClientRegistry.bindTileEntitySpecialRenderer(TileEntityCustomCauldronCookingOne.class, new customRendererCauldronCookingOne());
		ClientRegistry.bindTileEntitySpecialRenderer(TileEntityCustomCauldronCookingTwo.class, new customRendererCauldronCookingTwo());
		ClientRegistry.bindTileEntitySpecialRenderer(TileEntityCustomHook.class, new customRendererHook());
		ClientRegistry.bindTileEntitySpecialRenderer(TileEntityCustomAppleHangingRed.class, new customRendererAppleHangingRed());
		ClientRegistry.bindTileEntitySpecialRenderer(TileEntityCustomAppleStandingRed.class, new customRendererAppleStandingRed());
		ClientRegistry.bindTileEntitySpecialRenderer(TileEntityCustomPearStandingYellow.class, new customRendererPearStandingYellow());
		ClientRegistry.bindTileEntitySpecialRenderer(TileEntityCustomPearHangingYellow.class, new customRendererPearHangingYellow());
		ClientRegistry.bindTileEntitySpecialRenderer(TileEntityCustomMugEmpty.class, new customRendererMugEmpty());
		ClientRegistry.bindTileEntitySpecialRenderer(TileEntityCustomMugBeer.class, new customRendererMugBeer());
		ClientRegistry.bindTileEntitySpecialRenderer(TileEntityCustomMushroomBrown.class, new customRendererMushroomBrown());
		ClientRegistry.bindTileEntitySpecialRenderer(TileEntityCustomMushroomRed.class, new customRendererMushroomRed());
		ClientRegistry.bindTileEntitySpecialRenderer(TileEntityCustomTrainingsDummy.class, new customRendererTrainingsDummy());
		ClientRegistry.bindTileEntitySpecialRenderer(TileEntityCustomPotionEmpty.class, new customRendererPotionEmpty());
		ClientRegistry.bindTileEntitySpecialRenderer(TileEntityCustomPotionRegenerationOne.class, new customRendererPotionRegenerationOne());
		ClientRegistry.bindTileEntitySpecialRenderer(TileEntityCustomAppleHangingGreen.class, new customRendererAppleHangingGreen());
		ClientRegistry.bindTileEntitySpecialRenderer(TileEntityCustomAppleStandingGreen.class, new customRendererAppleStandingGreen());
		ClientRegistry.bindTileEntitySpecialRenderer(TileEntityCustomAppleHangingYellow.class, new customRendererAppleHangingYellow());
		ClientRegistry.bindTileEntitySpecialRenderer(TileEntityCustomAppleStandingYellow.class, new customRendererAppleStandingYellow());
		ClientRegistry.bindTileEntitySpecialRenderer(TileEntityCustomShipSteeringWheel.class, new customRendererShipSteeringWheel());
		ClientRegistry.bindTileEntitySpecialRenderer(TileEntityCustomKeyHanging.class, new customRendererKeyHanging());
		ClientRegistry.bindTileEntitySpecialRenderer(TileEntityCustomBarrelGunPowder.class, new customRendererBarrelGunPowder());
		ClientRegistry.bindTileEntitySpecialRenderer(TileEntityCustomBucketWater.class, new customRendererBucketWater());
		ClientRegistry.bindTileEntitySpecialRenderer(TileEntityCustomAnvil.class, new customRendererAnvil());
		ClientRegistry.bindTileEntitySpecialRenderer(TileEntityCustomWallTorchEmpty.class, new customRendererWallTorchEmpty());
		ClientRegistry.bindTileEntitySpecialRenderer(TileEntityCustomWallTorchLit.class,new customRendererWallTorchLit());
		ClientRegistry.bindTileEntitySpecialRenderer(TileEntityCustomWallTorchUnlit.class,new customRendererWallTorchUnlit());
	}
	
	public void registerRenders(){
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(itemFlour.itemFlour,0, new ModelResourceLocation(DarkRoleplay.MODID + ":"+"itemFlour","inventory"));
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(itemPear.itemPear,0, new ModelResourceLocation(DarkRoleplay.MODID + ":"+"itemPear","inventory"));
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(itemVegieStew.itemVegieStew,0, new ModelResourceLocation(DarkRoleplay.MODID + ":"+"itemVegieStew","inventory"));
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(itemPumpkinStew.itemPumpkinStew,0, new ModelResourceLocation(DarkRoleplay.MODID + ":"+"itemPumpkinStew","inventory"));
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(Item.getItemFromBlock(blockPlaceholder.blockPlaceholder),0, new ModelResourceLocation(DarkRoleplay.MODID + ":"+"blockPlaceholder","inventory"));
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(itemDough.itemDough,0, new ModelResourceLocation(DarkRoleplay.MODID + ":"+"itemDough","inventory"));
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(itemAppleYellow.itemAppleYellow,0, new ModelResourceLocation(DarkRoleplay.MODID + ":" + "itemAppleYellow","inventory"));
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(itemAppleGreen.itemAppleGreen,0, new ModelResourceLocation(DarkRoleplay.MODID + ":"+"itemAppleGreen","inventory"));
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(itemFirewood.itemFirewood,0, new ModelResourceLocation(DarkRoleplay.MODID + ":"+"itemFirewood","inventory"));
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(Item.getItemFromBlock(ChoppingBlock.blockChoppingBlock),0, new ModelResourceLocation(DarkRoleplay.MODID + ":"+"DarkRoleplayBlockChoppingBlock","inventory"));
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(itemBatEar.itemBatEar,0, new ModelResourceLocation(DarkRoleplay.MODID + ":"+"itemBatEar","inventory"));
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(itemFurWolf.itemFurWolf,0, new ModelResourceLocation(DarkRoleplay.MODID + ":"+"itemFurWolf","inventory"));
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(Item.getItemFromBlock(HangingBridgeOne.blockHangingBridgeOne),0, new ModelResourceLocation(DarkRoleplay.MODID + ":"+"blockHangingBridgeOne","inventory"));
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(Item.getItemFromBlock(DungeonChest.blockDungeonChest),0, new ModelResourceLocation(DarkRoleplay.MODID + ":"+"blockDungeonChest","inventory"));
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(Item.getItemFromBlock(BarrelEmpty.blockBarrelEmpty),0, new ModelResourceLocation(DarkRoleplay.MODID + ":"+"blockBarrelEmpty","inventory"));
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(Item.getItemFromBlock(BucketDirt.blockBucketDirt),0, new ModelResourceLocation(DarkRoleplay.MODID + ":"+"blockBucketDirt","inventory"));
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(Item.getItemFromBlock(BucketEmpty.blockBucketEmpty),0, new ModelResourceLocation(DarkRoleplay.MODID + ":"+"blockBucketEmpty","inventory"));
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(Item.getItemFromBlock(BucketFlowerOne.blockBucketFlowerOne),0, new ModelResourceLocation(DarkRoleplay.MODID + ":"+"blockBucketFlowerOne","inventory"));
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(Item.getItemFromBlock(Crate.blockCrate),0, new ModelResourceLocation(DarkRoleplay.MODID + ":"+"blockCrate","inventory"));
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(Item.getItemFromBlock(HangingBridgeTwo.blockHangingBridgeTwo),0, new ModelResourceLocation(DarkRoleplay.MODID + ":"+"blockHangingBridgeTwo","inventory"));
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(Item.getItemFromBlock(LargeFirepit.blockLargeFirepit),0, new ModelResourceLocation(DarkRoleplay.MODID + ":"+"blockLargeFirepit","inventory"));
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(Item.getItemFromBlock(SmallFirepit.blockSmallFirepit),0, new ModelResourceLocation(DarkRoleplay.MODID + ":"+"blockSmallFirepit","inventory"));
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(Item.getItemFromBlock(BarrelClosed.blockBarrelClosed),0, new ModelResourceLocation(DarkRoleplay.MODID + ":"+"blockBarrelClosed","inventory"));
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(Item.getItemFromBlock(ChoppingBlock.blockChoppingBlock),0, new ModelResourceLocation(DarkRoleplay.MODID + ":"+"blockChoppingBlock","inventory"));
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(Item.getItemFromBlock(Rope.blockRope),0, new ModelResourceLocation(DarkRoleplay.MODID + ":"+"blockRope","inventory"));
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(Item.getItemFromBlock(Cauldron.blockCauldron),0, new ModelResourceLocation(DarkRoleplay.MODID + ":"+"blockCauldron","inventory"));
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(Item.getItemFromBlock(Chain.blockChain),0, new ModelResourceLocation(DarkRoleplay.MODID + ":"+"blockChain","inventory"));
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(Item.getItemFromBlock(Grindstone.blockGrindstone),0, new ModelResourceLocation(DarkRoleplay.MODID + ":"+"blockGrindstone","inventory"));
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(Item.getItemFromBlock(TombstoneOne.blockTombstoneOne),0, new ModelResourceLocation(DarkRoleplay.MODID + ":"+"blockTombstoneOne","inventory"));
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(Item.getItemFromBlock(BookOne.blockBookOne),0, new ModelResourceLocation(DarkRoleplay.MODID + ":"+"blockBookOne","inventory"));
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(Item.getItemFromBlock(CauldronCookingOne.blockCauldronCookingOne),0, new ModelResourceLocation(DarkRoleplay.MODID + ":"+"blockCauldronCookingOne","inventory"));
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(Item.getItemFromBlock(Hook.blockHook),0, new ModelResourceLocation(DarkRoleplay.MODID + ":"+"blockHook","inventory"));
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(Item.getItemFromBlock(AppleHangingRed.blockAppleHangingRed),0, new ModelResourceLocation(DarkRoleplay.MODID + ":"+"blockAppleHangingRed","inventory"));
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(Item.getItemFromBlock(AppleStandingRed.blockAppleStandingRed),0, new ModelResourceLocation(DarkRoleplay.MODID + ":"+"blockAppleStandingRed","inventory"));
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(Item.getItemFromBlock(PearHangingYellow.blockPearHangingYellow),0, new ModelResourceLocation(DarkRoleplay.MODID + ":"+"blockPearHangingYellow","inventory"));
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(Item.getItemFromBlock(PearStandingYellow.blockPearStandingYellow),0, new ModelResourceLocation(DarkRoleplay.MODID + ":"+"blockPearStandingYellow","inventory"));
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(Item.getItemFromBlock(MugEmpty.blockMugEmpty),0, new ModelResourceLocation(DarkRoleplay.MODID + ":"+"blockMugEmpty","inventory"));
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(Item.getItemFromBlock(MugBeer.blockMugBeer),0, new ModelResourceLocation(DarkRoleplay.MODID + ":"+"blockMugBeer","inventory"));
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(Item.getItemFromBlock(MushroomBrown.blockMushroomBrown),0, new ModelResourceLocation(DarkRoleplay.MODID + ":"+"blockMushroomBrown","inventory"));
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(Item.getItemFromBlock(MushroomRed.blockMushroomRed),0, new ModelResourceLocation(DarkRoleplay.MODID + ":"+"blockMushroomRed","inventory"));
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(Item.getItemFromBlock(TrainingsDummy.blockTrainingsDummy),0, new ModelResourceLocation(DarkRoleplay.MODID + ":"+"blockTrainingsDummy","inventory"));
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(Item.getItemFromBlock(PotionEmpty.blockPotionEmpty),0, new ModelResourceLocation(DarkRoleplay.MODID + ":"+"blockPotionEmpty","inventory"));
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(Item.getItemFromBlock(PotionRegenerationOne.blockPotionRegenerationOne),0, new ModelResourceLocation(DarkRoleplay.MODID + ":"+"blockPotionRegenerationOne","inventory"));
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(Item.getItemFromBlock(AppleHangingGreen.blockAppleHangingGreen),0, new ModelResourceLocation(DarkRoleplay.MODID + ":"+"blockAppleHangingGreen","inventory"));
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(Item.getItemFromBlock(AppleStandingGreen.blockAppleStandingGreen),0, new ModelResourceLocation(DarkRoleplay.MODID + ":"+"blockAppleStandingGreen","inventory"));
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(Item.getItemFromBlock(AppleHangingYellow.blockAppleHangingYellow),0, new ModelResourceLocation(DarkRoleplay.MODID + ":"+"blockAppleHangingYellow","inventory"));
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(Item.getItemFromBlock(AppleStandingYellow.blockAppleStandingYellow),0, new ModelResourceLocation(DarkRoleplay.MODID + ":"+"blockAppleStandingYellow","inventory"));
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(Item.getItemFromBlock(BucketWater.blockBucketWater), 0, new ModelResourceLocation(DarkRoleplay.MODID + ":" + "blockBucketWater", "inventory"));
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(Item.getItemFromBlock(BarrelGunPowder.blockBarrelGunPowder), 0, new ModelResourceLocation(DarkRoleplay.MODID + ":" + "blockBarrelGunPowder", "inventory"));
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(Item.getItemFromBlock(ShipSteeringWheel.blockShipSteeringWheel), 0, new ModelResourceLocation(DarkRoleplay.MODID + ":" + "blockShipSteeringWheel", "inventory"));
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(Item.getItemFromBlock(Target.blockTarget), 0, new ModelResourceLocation(DarkRoleplay.MODID + ":" + "blockTarget", "inventory"));
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(Item.getItemFromBlock(KeyHanging.blockKeyHanging), 0, new ModelResourceLocation(DarkRoleplay.MODID + ":" + "blockKeyHanging", "inventory"));
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(itemCoinBronze.itemCoinBronze,0,new ModelResourceLocation(DarkRoleplay.MODID + ":" + "itemCoinBronze", "inventory"));
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(itemCoinSilver.itemCoinSilver,0,new ModelResourceLocation(DarkRoleplay.MODID + ":" + "itemCoinSilver", "inventory"));
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(itemCoinGold.itemCoinGold,0,new ModelResourceLocation(DarkRoleplay.MODID + ":" + "itemCoinGold", "inventory"));
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(itemPurse.itemPurse,0,new ModelResourceLocation(DarkRoleplay.MODID + ":" + "itemPurse", "inventory"));
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(itemScrollTeleport.itemScrollTeleport,0,new ModelResourceLocation(DarkRoleplay.MODID + ":" + "itemScrollTeleport", "inventory"));
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(Item.getItemFromBlock(Anvil.blockAnvil),0, new ModelResourceLocation(DarkRoleplay.MODID + ":" + "blockAnvil", "inventory"));//ANVIL
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(RingIron.RingIron, 0, new ModelResourceLocation(DarkRoleplay.MODID + ":" + "RingIron", "inventory"));
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(potionMana1.potionMana1,0, new ModelResourceLocation(DarkRoleplay.MODID + ":" + "potionMana1", "inventory"));
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(Item.getItemFromBlock(WallTorchEmpty.blockWallTorchEmpty),0,new ModelResourceLocation(DarkRoleplay.MODID + ":" + "blockWallTorchEmpty","inventory"));
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(Item.getItemFromBlock(WallTorchLit.blockWallTorchLit),0,new ModelResourceLocation(DarkRoleplay.MODID + ":" + "blockWallTorchLit","inventory"));
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(Item.getItemFromBlock(WallTorchUnlit.blockWallTorchUnlit),0,new ModelResourceLocation(DarkRoleplay.MODID + ":" + "blockWallTorchUnlit","inventory"));
		Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(Item.getItemFromBlock(CauldronCookingTwo.blockCauldronCookingTwo),0,new ModelResourceLocation(DarkRoleplay.MODID + ":" + "blockCauldronCookingTwo","inventory"));
	}
	
	public World getClientWorld(){
		return FMLClientHandler.instance().getClient().theWorld;
	}
}
